### ISSUE TITLE
Randomly errors?

### ISSUE THREAD

**Issue by thenoid** [ibielopolskyi/smartthings_fridge_camera#3]
```homeassistant    | 2024-03-07 19:42:34.464 ERROR (MainThread) [custom_components.samsung_familyhub_fridge.api] Unexpected error fetching File ID refresher data: 'items'
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
homeassistant    |     self.data = await self._async_update_data()
homeassistant    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant    |   File "/config/custom_components/samsung_familyhub_fridge/api.py", line 66, in _async_update_data
homeassistant    |     raise err
homeassistant    |   File "/config/custom_components/samsung_familyhub_fridge/api.py", line 54, in _async_update_data
homeassistant    |     elif set(self.last_file_ids) != set(self.api.get_file_ids()):
homeassistant    |                                         ^^^^^^^^^^^^^^^^^^^^^^^
homeassistant    |   File "/config/custom_components/samsung_familyhub_fridge/api.py", line 148, in get_file_ids
homeassistant    |     for element in self._device_status["items"]:
homeassistant    |                    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
homeassistant    | KeyError: 'items'
```

**Comment by ibielopolskyi** [comment]
Seems like it's throttling the status queries. I published a new commit that should be taking care of it. Take a look at #5
