### ISSUE TITLE
Unexpected error fetching File ID refresher data: 'items'

### ISSUE THREAD

**Issue by dajomas** [ibielopolskyi/smartthings_fridge_camera#5]
At some point, errors start to occur in the logfile. First it is this error:
```
2024-03-28 06:06:19.507 ERROR (MainThread) [custom_components.samsung_familyhub_fridge.api] Unexpected error fetching File ID refresher data: 'items'
Traceback (most recent call last):
  File "/srv/Python-3.12.2/HASS-2024.3.3/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 66, in _async_update_data
    raise err
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 63, in _async_update_data
    self.api.extract_device_data()
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 132, in extract_device_data
    for element in self._device_status["items"]:
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
```

Then, every 10 seconds, this error occurs (filling up the logfile):
```
2024-03-28 06:06:29.346 ERROR (MainThread) [custom_components.samsung_familyhub_fridge.api] Unexpected error fetching File ID refresher data: 'items'
Traceback (most recent call last):
  File "/srv/Python-3.12.2/HASS-2024.3.3/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 66, in _async_update_data
    raise err
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 54, in _async_update_data
    elif set(self.last_file_ids) != set(self.api.get_file_ids()):
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 148, in get_file_ids
    for element in self._device_status["items"]:
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
```

I did a small check and this is the contents of ```self._device_status``` (requestId is hidden):
```python
{
  'requestId': '***',
  'error': {
    'code': 'UnexpectedError',
    'target': None,
    'message': 'A non-recoverable error condition occurred.',
    'details': []
  }
}
```

After this, the camera image does no longer refresh

**Comment by dajomas** [comment]
I checked the contents of self._device_status by adding the following lines in function ```set_device_status``` (after line 99):

```python
        if "items" not in self._device_status.keys():
            _LOGGER.info(self._device_status)
```

**Comment by ibielopolskyi** [comment]
I'm seeing the same issue. Most probably, Smartthings changed something in the API. I'm looking into it,

**Comment by ibielopolskyi** [comment]
Alright, try with the latest commit. (probably disable for a bit so that the status query can go through at least once)

**Comment by dajomas** [comment]
Unfortunately, this issue still exists and no images are available until I restart HA
