### ISSUE TITLE
Unexpected error fetching File ID refresher data: 'samsungce.viewInside'

### ISSUE THREAD

**Issue by ronluna** [ibielopolskyi/smartthings_fridge_camera#7]
Have not been able to get it to pull any images. Here is what the logs shows.

'''
Unexpected error fetching File ID refresher data: 'samsungce.viewInside'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_familyhub_fridge/api.py", line 51, in _async_update_data
    elif set(self.last_file_ids) != set(self.api.get_file_ids()):
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_familyhub_fridge/api.py", line 146, in get_file_ids
    element = self._current_device_status["samsungce.viewInside"]["contents"]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'samsungce.viewInside'
'''

any ideas ?

**Comment by ronluna** [comment]
So this Samsung Chef Collection Fridge with cameras just like the family hub one. I've testing the addon on a Family Hub fridge and the snapshots are coming just fine.... Both fridge have been added to smartthing and even though one is listed as a Family Hub Fridge and the other as a Chef Collection Fridge the snapshots from the cameras work just fine for both of them (When using the official smartthing app) .  I did noticed that they are using different profile ids

The Family Hub Fridge is using DA-REF-NORMAL-01001 and the Chef Collection is using DA-REF-NORMAL-000001 I also noticed that the components id on each profile are different. So I'm wondering if there is any way to get this profile also working with the addon ?

**Comment by dajomas** [comment]
I have done a little bit of research on this issue as I am running into it myself as well.

Initially, the call is successful and then at a certain point, the following error appears once, followed by the earlier mentioned error (KeyError: ' samsungce.vieInside') continuously:
```
2024-08-30 20:08:32.679 ERROR (MainThread) [custom_components.samsung_familyhub_fridge.api] Unexpected error fetching File ID refresher data
Traceback (most recent call last):
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 60, in _async_update_data
    self.api.extract_device_data()
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 138, in extract_device_data
    contact = self._current_device_status["contactSensor"]["contact"]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'contactSensor'
```
 
After this, the value of ```self._current_device_status``` looks like this:
```
{
	"requestId": "***********",
	"error": {
		"code": "UnexpectedError",
		"message": "A non-recoverable error condition occurred.",
		"details": []
	}
}
```

After this, the following error keeps popping up every couple of seconds:
```
2024-08-30 20:08:42.513 ERROR (MainThread) [custom_components.samsung_familyhub_fridge.api] Unexpected error fetching File ID refresher data
Traceback (most recent call last):
  File "/srv/Python-3.12.5/HASS-2024.8.3/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 51, in _async_update_data
    elif set(self.last_file_ids) != set(self.api.get_file_ids()):
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/samsung_familyhub_fridge/api.py", line 147, in get_file_ids
    element = self._current_device_status["samsungce.viewInside"]["contents"]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'samsungce.viewInside'
```

I am running HA Core 2024.8.3 using Python 3.12.5. I have a Samsung Family Hub with a single camera

**Comment by dajomas** [comment]
Just for completion sake, the value of ```self._current_device_status["samsungce.viewInside"]``` looks like this when the errors do not occur:
```
"samsungce.viewInside": {
		"supportedFocusAreas": {
			"value": [
				"mainShelves"
			],
			"timestamp": "2023-12-15T01:10:13.942Z"
		},
		"contents": {
			"value": [
				{
					"fileId": "********-****-****-****-************",
					"mimeType": "image/jpeg",
					"expiredTime": "2024-08-30T08:33:59Z",
					"focusArea": "mainShelves"
				}
			],
			"timestamp": "2024-08-30T08:23:59.209Z"
		},
		"lastUpdatedTime": {
			"value": "2024-08-30T06:23:11Z",
			"timestamp": "2024-08-30T08:23:59.209Z"
		}
	}
```

**Comment by dajomas** [comment]
Finally, this issue is not triggered by opening and closing the door, nor by accessing the camera image via HA as I have tried that multiple times without the error occurring

**Comment by Krzysztonek** [comment]
same issue here:

```
Unexpected error fetching File ID refresher data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_familyhub_fridge/api.py", line 66, in _async_update_data
    raise err
  File "/config/custom_components/samsung_familyhub_fridge/api.py", line 54, in _async_update_data
    elif set(self.last_file_ids) != set(self.api.get_file_ids()):
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_familyhub_fridge/api.py", line 148, in get_file_ids
    for element in self._device_status["items"]:
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
```

**Comment by ronluna** [comment]
For me the snapshot is not coming in ...

```
Logger: custom_components.samsung_familyhub_fridge.api
Source: helpers/update_coordinator.py:432
integration: Samsung FamilyHub Fridge ([documentation](https://github.com/ibielopolskyi/smartthings_fridge_camera), [issues](https://github.com/ibielopolskyi/smartthings_fridge_camera/issues))
First occurred: April 10, 2026 at 10:29:27 PM (17 occurrences)
Last logged: 3:16:01 PM

Timeout fetching File ID refresher data
```

**Comment by ibielopolskyi** [comment]
Yeah, I recently picked up this integration that I haven’t been using in a while. FWIW, Samsung now exposes this in smart things so all these workarounds might not be needed anymore
